<?php
/* @var $block \MageDemo\FlashSale\Block\Timer;
 */
$_product = $block->getProduct();
$text = $block->getString();
?>

<div class="flash-sale-container">
    <span><?= $text; ?></span>
    <div class="timer-wrapper" data-bind="scope:'flash_timer'">
        <h2 data-bind="text: heading"></h2>
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "flash_timer": {
                    "component": "MageDemo_FlashSale/js/knockout-timer",
                    "timerMessage": "<?= $_product->getName(); ?>"
                }
            }
        }
    }
}
</script>
